# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import contact_pb2 as contact__pb2


class ContactStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendStatus = channel.stream_stream(
        '/Contact/sendStatus',
        request_serializer=contact__pb2.ClientMsg.SerializeToString,
        response_deserializer=contact__pb2.Result.FromString,
        )
    self.getTask = channel.unary_stream(
        '/Contact/getTask',
        request_serializer=contact__pb2.Empty.SerializeToString,
        response_deserializer=contact__pb2.ServerMsg.FromString,
        )
    self.tellResult = channel.stream_unary(
        '/Contact/tellResult',
        request_serializer=contact__pb2.Result.SerializeToString,
        response_deserializer=contact__pb2.Empty.FromString,
        )


class ContactServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendStatus(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def tellResult(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ContactServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendStatus': grpc.stream_stream_rpc_method_handler(
          servicer.sendStatus,
          request_deserializer=contact__pb2.ClientMsg.FromString,
          response_serializer=contact__pb2.Result.SerializeToString,
      ),
      'getTask': grpc.unary_stream_rpc_method_handler(
          servicer.getTask,
          request_deserializer=contact__pb2.Empty.FromString,
          response_serializer=contact__pb2.ServerMsg.SerializeToString,
      ),
      'tellResult': grpc.stream_unary_rpc_method_handler(
          servicer.tellResult,
          request_deserializer=contact__pb2.Result.FromString,
          response_serializer=contact__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Contact', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
